language: ruby
cache: bundler
rvm:
- 2.3.0
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rake db:schema:load
- bundle exec rake
- bundle exec rake rubocop
services:
- postgresql